[package]
name = "audio_x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
id3 = "1.14.0"
ratatui = "0.28.0"
rodio = "0.19.0"
